context("Data Operations")

test_that("Testing proper response to math operators", {
    # operations that are not meaningful ===========
    expect_is(r <- ratio(0.1), "Ratio")
    expect_is(i <- intensity(100), "Intensity")
    expect_is(rs <- ratio(0.1, 0.2), "Ratios")
    expect_is(is <- intensity(100, 1000), "Intensities")
    expect_error(r + 5, "Addition .* not meaningful")
    expect_error(5 + r, "Addition .* not meaningful")
    expect_error(r + i, "Addition .* not meaningful")
    expect_error(r + is, "Addition .* not meaningful")
    expect_error(rs + is, "Addition .* not meaningful")
    expect_error(r - 5, "Subtraction .* not meaningful")
    expect_error(5 - r, "Subtraction .* not meaningful")
    expect_error(r - i, "Subtraction .* not meaningful")
    expect_error(r - is, "Subtraction .* not meaningful")
    expect_error(rs - is, "Subtraction .* not meaningful")
    expect_error(r * 5, "Multiplication .* not meaningful")
    expect_error(5 * r, "Multiplication .* not meaningful")
    expect_error(r * i, "Multiplication .* not meaningful")
    expect_error(r * is, "Multiplication .* not meaningful")
    expect_error(rs * is, "Multiplication .* not meaningful")
    expect_error(r / 5, "Division .* not meaningful")
    expect_error(5 / r, "Division .* not meaningful")
    expect_error(r / i, "Division .* not meaningful")
    expect_error(r / is, "Division .* not meaningful")
    expect_error(rs / is, "Division .* not meaningful")
    
    # operations that are permitted and implemented ===========
    # converting intensity to ratio 
    expect_error(intensity(100, unit = "mV") / intensity(1000), "cannot generate an isotope ratio from two intensity objects with differing units")
    expect_error(intensity(100, unit = "mV") / intensity(1000, unit = "V"), "cannot generate an isotope ratio from two intensity objects with differing units")
    expect_error(intensity(1:5) / intensity(2:3), "longer object length is not a multiple of shorter object length")
    expect_is(r <- intensity(`13C` = 1:5) / intensity(`12C` = 5:9), "Ratio")
    expect_equal(as.numeric(r), 1:5/5:9)
    expect_equal(r@isoname, "13C")
    expect_equal(r@major, "12C")
})